{% set name = "oxasl_ve" %}
{% set version = "0.1.1.post2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/oxasl-ve-{{ version }}.tar.gz
  sha256: 4a13c3f75d68209399924480e5ee91fe518b5381e70fe33a4bd12d68a6ab7b6e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - fslpy >=1.13
    - numpy
    - oxasl
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - oxasl_ve
    - oxasl_ve.wrappers

about:
  home: https://oxasl.readthedocs.io/
  summary: Python library for manipulating and modelling ASL data
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mcraig-ibme
